name: TestPR

on: pull_request
  branches:
      - master
  paths: test.md
  type: closed

jobs:
  job1:
    runs-on: ubuntu-latest
    if github.event.pull_request.merged == true
    steps:
      run: echo This event is a pull request that had an assignee removed.
